version: '2'
services:
  PostgreSQL:
    container_name: PostgreTestsClock
    image: postgres:10-alpine
    ports:
      - '5531:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
      # - ./postgres.conf:/etc/postgresql/postgresql.conf
    # command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
